name: Lint notebooks

on:
  push:
    branches:
      - main
    paths:
      - notebooks/**
  pull_request:
    branches:
      - main
    paths:
      - notebooks/**

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd notebooks
          virtualenv embed
          source embed/bin/activate
          pip3 install black[jupyter]
          if [ -f notebooks/requirements.txt ]; then pip install -r notebooks/requirements.txt; fi
      - name: Format with black 
        run: |
          cd notebooks
          black .
